CREATE DATABASE IF NOT EXISTS readme
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE readme;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date_reg DATETIME,
  email VARCHAR(128) NOT NULL UNIQUE,
  user_name VARCHAR(128),
  user_password VARCHAR(128),
  avatar_path VARCHAR(255)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS types (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128),
  class VARCHAR(128)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date_great DATETIME,
  title VARCHAR(255),
  content TEXT,
  author_quote VARCHAR(128),
  img_path VARCHAR(255),
  video_path VARCHAR(255),
  link VARCHAR(255),
  count INT UNSIGNED,
  user_id INT UNSIGNED,
  type_id INT UNSIGNED,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (type_id) REFERENCES types(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS comments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date_great DATETIME,
  content TEXT,
  user INT UNSIGNED,
  post INT UNSIGNED,
  FOREIGN KEY (user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (post) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS likes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_like INT UNSIGNED,
  post_like INT UNSIGNED,
  FOREIGN KEY (user_like) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (post_like) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS subscriptions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  author INT UNSIGNED,
  subscription INT UNSIGNED,
  FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (subscription) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS messages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date_great DATETIME,
  content TEXT,
  sender INT UNSIGNED,
  recipient INT UNSIGNED,
  FOREIGN KEY (sender) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (recipient) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS hashtags (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS posts_hashtags (
  id_post INT UNSIGNED NOT NULL,
  id_hashtag INT UNSIGNED NOT NULL,
  PRIMARY KEY (id_post, id_hashtag),
  FOREIGN KEY (id_post) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (id_hashtag) REFERENCES hashtags(id) ON DELETE CASCADE
) ENGINE = InnoDB;
